### ISSUE TITLE
Unexpected Error when trying to login

### ISSUE THREAD

**Issue by ryan-exley** [imhotep/hass-unifi-access#88]
**Describe the bug**
Getting unexpected error when to to initially log into the integration.
I am a Unifi Enterprise (Free) user so I have had to generate my API key from Identity Enterprise online not from the controller itself

For host I have tried IP of controller and the enterprise host name "/gw" but both have no success

From what I can tell its an issue with the host name

**Which Hub are you using**
1. Unifi Access Hub

**Screenshots**
NA

**Versions:**
 - Home Assistant version 2024.12.1
 - Unifi Access version 2.5.2
 - Unifi Access Integration version 1.2.5

**Home Assistant DEBUG logs (MANDATORY)**
This error originated from a custom integration.

Logger: custom_components.unifi_access.config_flow
Source: custom_components/unifi_access/config_flow.py:69
integration: Unifi Access
First occurred: 12:30:21 (2 occurrences)
Last logged: 12:31:59

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/unifi_access/config_flow.py", line 69, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/unifi_access/config_flow.py", line 37, in validate_input
    auth_response = await hass.async_add_executor_job(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        api.authenticate, data["api_token"]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/unifi_access/hub.py", line 171, in authenticate
    self.update()
    ~~~~~~~~~~~^^
  File "/config/custom_components/unifi_access/hub.py", line 122, in update
    data = self._make_http_request(f"{self.host}{DOORS_URL}")
  File "/config/custom_components/unifi_access/hub.py", line 250, in _make_http_request
    r = request(
        method,
    ...<4 lines>...
        timeout=10,
    )
  File "/usr/local/lib/python3.13/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.13/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
    ~~~~~~~~~^
        method=request.method.upper(),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<10 lines>...
        hooks=merge_hooks(request.hooks, self.hooks),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 367, in prepare
    self.prepare_url(url, params)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 444, in prepare_url
    raise InvalidURL(f"Invalid URL {url!r}: No host supplied")
requests.exceptions.InvalidURL: Invalid URL 'https:///gw:12445/api/v1/developer/doors': No host supplied

**Comment by imhotep** [comment]
Please refer to the `README.md`. UID Enterprise is NOT officially [supported](https://github.com/imhotep/hass-unifi-access?tab=readme-ov-file#unifi-access-custom-integration-for-home-assistant).
